### ISSUE TITLE
Localization of the survey

### ISSUE THREAD

**Issue by jamshidhashimi** [ddlibrary/website#14]
Survey questions, survey answers and survey options should all all support localization. This means we should be able to translate the questions, answers and options in all the languages DDL supports.

**Comment by jamshidhashimi** [comment]
@shakour-ghafarzoy if this was done, I can close this issue.

**Comment by shakour-ghafarzoy** [comment]
@jamshidhashimi Jan, did you implement the deployment notes?
If everything is working as expected, then yes you can close it.
