### ISSUE TITLE
Menu items translation

### ISSUE THREAD

**Issue by jamshidhashimi** [ddlibrary/website#45]
The menu section needs translation in the admin panel. Admins should be able to add translations directly from the menu section in the admin panel.

**Comment by jamshidhashimi** [comment]
@abubaker47 please verify everything working fine and then close this issue.

**Comment by abubaker47** [comment]
@jamshidhashimi I have checked it works fine, do close this issue.

**Comment by jamshidhashimi** [comment]
Thanks for confirming @abubaker47.
