### ISSUE TITLE
Persian/Farsi Font

### ISSUE THREAD

**Issue by jamshidhashimi** [ddlibrary/website#62]
For our non-English content, we need a Persian/Farsi font to be used, so to make the appearance of contents easy to read. The current font is fine, but looking at websites like http://www.bbc.com/persian/afghanistan,  8am.af or https://www.etilaatroz.com/ we can do much improvements.

**Comment by hamidafghan** [comment]
For Persian content, I suggest the **Bahij Nazanin** font while the MCIT portals are using it. You can find it [here](https://github.com/hamidafghan/bahij-nazanin-font).

**Comment by jamshidhashimi** [comment]
Thank you very much @hamidafghan. @abubaker47 can you please check it?

**Comment by abubaker47** [comment]
Thanks @hamidafghan I will check it.

**Comment by jamshidhashimi** [comment]
@abubaker47 Jan, I merged https://github.com/ddlibrary/website/pull/67. Please make sure everything is working fine and then close this issue.

**Comment by abubaker47** [comment]
I have checked, everything works fine. you can close the issue now.
