### ISSUE TITLE
New Survey Report UI

### ISSUE THREAD

**Issue by jamshidhashimi** [ddlibrary/website#68]
The new survey report UI is not user friendly and the table is showing missing information. Additionally, the Descriptive section is empty in both web and Excel version. 

The new survey report was added as part of this PR: https://github.com/ddlibrary/website/pull/54/

**Comment by jamshidhashimi** [comment]
I merged the PR: https://github.com/ddlibrary/website/pull/69 and pushed the code to the production. Please make sure everything is working fine and then close this issue.

**Comment by abubaker47** [comment]
I have checked the report it works fine the descriptive and responsiveness issue is solved.

**Comment by jamshidhashimi** [comment]
Thanks for confirming @abubaker47. Closing this issue.
