### ISSUE TITLE
English Language hint on Resources keywords

### ISSUE THREAD

**Issue by abubaker47** [ddlibrary/website#70]
Adding or editing resources on local languages is difficult for those who don't know the local languages such as Auzbiki, Munji, suji, and others so a hint on the English language for keywords will be helpful.

**Comment by jamshidhashimi** [comment]
@abubaker47  I merged and pushed the code to the production (PR: https://github.com/ddlibrary/website/pull/63). Please make sure everything is working fine and after, you can close this issue.
